name: Terraform State Import Test
on:
  workflow_dispatch:
    inputs:
      jobToRun:
        description: 'Select Job'
        required: true
        default: 'TfState'
        type: choice
        options:
          - TfState
env:
  terraformVersion: '1.8.0'

permissions:
  id-token: write
  contents: read
  issues: write

jobs:
  TfState:
    if: ${{ github.event.inputs.jobToRun == 'TfState' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_backend_resource_group_name: ${{ secrets.BACKEND_RESOURCE_GROUP_NAME }}
          TF_VAR_backend_storage_account_name: ${{ secrets.BACKEND_STORAGE_ACCOUNT_NAME }}
          TF_VAR_backend_container_name: ${{ secrets.BACKEND_CONTAINER_NAME }}
          TF_VAR_backend_key: netrules.terraform.tfstate
        run: |
          cd modules/networkrules
          terraform init \
            -backend-config="resource_group_name=${TF_VAR_backend_resource_group_name}" \
            -backend-config="storage_account_name=${TF_VAR_backend_storage_account_name}" \
            -backend-config="container_name=${TF_VAR_backend_container_name}" \
            -backend-config="key=${TF_VAR_backend_key}"

      - name: Terraform Plan Network Rules
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_backend_resource_group_name: ${{ secrets.BACKEND_RESOURCE_GROUP_NAME }}
          TF_VAR_backend_storage_account_name: ${{ secrets.BACKEND_STORAGE_ACCOUNT_NAME }}
          TF_VAR_backend_container_name: ${{ secrets.BACKEND_CONTAINER_NAME }}
          TF_VAR_backend_key: netrules.terraform.tfstate
        run: |
          cd modules/networkrules
          terraform plan -out=tfplan
          terraform show -no-color tfplan > plan.txt  

      - name: Upload .terraform.lock.hcl
        uses: actions/upload-artifact@v4
        with:
          name: terraform-workspace
          path: /home/runner/work/plateng-azure-inf-LZ/plateng-azure-inf-LZ/modules/networkrules/.terraform.lock.hcl
          include-hidden-files: true

      - name: Upload plan.txt artifact
        uses: actions/upload-artifact@v4
        with:
          name: plan-txt-artifact
          path: modules/networkrules/plan.txt

      - name: Upload tfplan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-artifact
          path: modules/networkrules/tfplan

      # - name: Await manual approval before apply
      #   if: success()
      #   uses: actions/github-script@v7
      #   environment: prod-approval
      #   with:
      #     script: |
      #       console.log("Waiting for environment approval...")

      - name: Await manual approval before apply
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: nishikant-zensar,nitin-zensar
          minimum-approvals: 1
          issue-title: "Manual approval required for Network Rules apply"
          issue-body: "Please approve to proceed with Terraform apply for Network Rules."
          exclude-workflow-initiator-as-approver: false
      
      - name: Terraform Apply Network Rules
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_backend_resource_group_name: ${{ secrets.BACKEND_RESOURCE_GROUP_NAME }}
          TF_VAR_backend_storage_account_name: ${{ secrets.BACKEND_STORAGE_ACCOUNT_NAME }}
          TF_VAR_backend_container_name: ${{ secrets.BACKEND_CONTAINER_NAME }}
          TF_VAR_backend_key: netrules.terraform.tfstate
        run: |
          cd modules/networkrules
          terraform apply -auto-approve tfplan
